import json
import sys
from pathlib import Path

ROOT = Path(r"D:\CODEX\XIHE-CRM")
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from utils.database import add_customer, init_db


def lead(
    company_name,
    city,
    website,
    industry,
    segment,
    account_type,
    keyword_cluster,
    buyer_type,
    business_model,
    facility_stage,
    buying_trigger,
    pain_point,
    economic_justification,
    product_fit,
    outreach_angle,
    fit_score,
    priority_level,
    decision_maker="",
    position="",
    email="",
    phone="",
    existing_equipment="",
    notes="",
    tags="",
    status="To Contact",
    priority="Medium",
    next_follow_up="2026-06-14",
    extended_info=None,
):
    return {
        "company_name": company_name,
        "country": "US",
        "city": city,
        "industry": industry,
        "segment": segment,
        "account_type": account_type,
        "keyword_cluster": keyword_cluster,
        "buyer_type": buyer_type,
        "business_model": business_model,
        "facility_stage": facility_stage,
        "buying_trigger": buying_trigger,
        "pain_point": pain_point,
        "economic_justification": economic_justification,
        "product_fit": product_fit,
        "outreach_angle": outreach_angle,
        "fit_score": fit_score,
        "priority_level": priority_level,
        "decision_maker": decision_maker,
        "position": position,
        "email": email,
        "phone": phone,
        "website": website,
        "existing_equipment": existing_equipment,
        "notes": notes,
        "tags": tags,
        "status": status,
        "priority": priority,
        "next_follow_up": next_follow_up,
        "extended_info": extended_info or {},
    }


def main():
    init_db()
    leads = [
        lead(
            company_name="Beacon Orthopaedics & Sports Medicine",
            city="Cincinnati/Dayton/NKY/Indiana",
            website="https://www.beaconortho.com/",
            industry="Medical Rehabilitation",
            segment="US sports medicine / ortho",
            account_type="Sports Medicine Clinic",
            keyword_cluster="sports medicine, physical therapy, return to play, post-op rehabilitation",
            buyer_type="PT Clinic Owner",
            business_model="Hybrid",
            facility_stage="Operating",
            buying_trigger="Return-to-Play Demand",
            pain_point="Premium recovery add-on, athlete-facing differentiation, post-session recovery workflow",
            economic_justification="Increase revenue per patient visit without adding therapist hours",
            product_fit="Graphene recovery environment / premium recovery suite",
            outreach_angle="A premium recovery environment beside PT and sports medicine services",
            fit_score=92,
            priority_level="Hot",
            decision_maker="Andy Blankemeyer",
            position="CEO",
            phone="513-354-3700",
            existing_equipment="sports medicine, PT, orthobiologics, walk-in clinic",
            notes="Public site shows 20+ locations and 60+ physicians; benchmark account for similar sports medicine groups.",
            tags="#SportsMedicine,#PT,#Recovery",
            extended_info={
                "research_date": "2026-06-13",
                "source": "Google Trends + website analysis",
                "segment": "sports medicine / ortho",
            },
        ),
        lead(
            company_name="Hospital for Special Surgery",
            city="New York, NY",
            website="https://www.hss.edu/",
            industry="Medical Rehabilitation",
            segment="Orthopaedic surgery / sports medicine",
            account_type="Hospital / Specialty Center",
            keyword_cluster="orthopaedic surgery, rehabilitation, sports medicine, return to play",
            buyer_type="Rehab Director",
            business_model="Hybrid",
            facility_stage="Operating",
            buying_trigger="Premium Experience Upgrade",
            pain_point="High-acuity athlete and surgery recovery flow",
            economic_justification="Differentiated recovery environment for patient experience and throughput",
            product_fit="Recovery environment / premium suite concept",
            outreach_angle="Premium recovery environment for orthopaedic and athlete rehabilitation",
            fit_score=81,
            priority_level="Warm",
            notes="Top orthopaedic specialty center; useful anchor account for surgical rehab positioning.",
            tags="#Orthopaedics,#SportsMedicine,#Rehab",
            extended_info={
                "research_date": "2026-06-13",
                "source": "Google Search",
                "segment": "orthopaedic specialty center",
            },
        ),
        lead(
            company_name="The Stone Clinic",
            city="San Francisco, CA",
            website="https://www.stoneclinic.com/",
            industry="Medical Rehabilitation",
            segment="Sports medicine / athlete recovery",
            account_type="Specialty Clinic",
            keyword_cluster="sports medicine, athlete recovery, return to play, rehabilitation",
            buyer_type="Clinic Owner",
            business_model="Hybrid",
            facility_stage="Operating",
            buying_trigger="Return-to-Play Demand",
            pain_point="Need strong athlete-facing recovery story",
            economic_justification="Premium recovery add-on aligned with elite athlete positioning",
            product_fit="Recovery suite / athlete recovery environment",
            outreach_angle="Premium athlete recovery environment to complement sports medicine",
            fit_score=79,
            priority_level="Warm",
            notes="Athlete recovery language appears in public positioning; useful sports-performance benchmark.",
            tags="#SportsMedicine,#AthleteRecovery,#Rehab",
            extended_info={
                "research_date": "2026-06-13",
                "source": "Google Search",
                "segment": "sports medicine clinic",
            },
        ),
        lead(
            company_name="UNM Health System - Center of Excellence for Orthopaedic Surgery & Rehabilitation",
            city="Albuquerque, NM",
            website="https://unmhealth.org/",
            industry="Medical Rehabilitation",
            segment="Orthopaedic surgery / rehabilitation",
            account_type="Hospital System",
            keyword_cluster="orthopaedic surgery, rehabilitation, sports medicine",
            buyer_type="Rehab Director",
            business_model="Hybrid",
            facility_stage="Operating",
            buying_trigger="Premium Experience Upgrade",
            pain_point="Need organized recovery flow for orthopaedic surgery and rehab",
            economic_justification="Higher-value rehab environment and patient experience",
            product_fit="Integrated recovery environment",
            outreach_angle="Orthopaedic recovery environment to improve rehab experience",
            fit_score=77,
            priority_level="Warm",
            notes="Search result showed orthopaedic surgery & rehabilitation center of excellence.",
            tags="#Orthopaedics,#Rehab,#Hospital",
            extended_info={
                "research_date": "2026-06-13",
                "source": "Google Search",
                "segment": "hospital rehab",
            },
        ),
        lead(
            company_name="American Orthopaedic Foot & Ankle Society",
            city="Rosemont, IL",
            website="https://www.aofas.org/",
            industry="Medical Rehabilitation",
            segment="Orthopaedic / professional society",
            account_type="Professional Association",
            keyword_cluster="orthopaedic surgery, rehab, sports medicine",
            buyer_type="Operations Lead",
            business_model="Membership",
            facility_stage="Operating",
            buying_trigger="Member Education / Clinical Authority",
            pain_point="Educational authority rather than direct clinical operations",
            economic_justification="Lower direct fit but useful for authority and referral ecosystem",
            product_fit="Educational / scientific outreach",
            outreach_angle="Authority-building rather than direct equipment sell",
            fit_score=48,
            priority_level="Low",
            status="Paused",
            priority="Low",
            next_follow_up="2026-06-21",
            notes="Not a direct buyer; keep for ecosystem mapping only.",
            tags="#Orthopaedics,#Association,#Authority",
            extended_info={
                "research_date": "2026-06-13",
                "source": "Google Search",
                "segment": "professional society",
            },
        ),
    ]

    ids = []
    for item in leads:
        ids.append(add_customer(item))

    print(json.dumps({"inserted_ids": ids}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
